# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e6p461XYCnke0aGCu2xW92mU05ilST9E
"""

#!pip install streamlit
import streamlit as st

import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
import pickle
import numpy as np
from tensorflow.keras.models import load_model

model = load_model("model.keras")
with open('label_enc_gender.pkl','rb') as file:
  label_enc_gender=pickle.load(file)
with open('onehot_enc_geo.pkl','rb') as file:
  onehot_enc_geo=pickle.load(file)
with open('scaler.pkl','rb') as file:
  scaler=pickle.load(file)

##steamlit app
st.title('Customer Churn Prediction')

geography=st.selectbox('Geography', onehot_enc_geo.categories_[0])
gender=st.selectbox('Gender',label_enc_gender.classes_)
age=st.slider('Age',18,90)
balance=st.number_input('Balance')
credit_score=st.number_input('CreditScore')
estimated_salary=st.number_input('Estimated Salary')
tenure=st.slider('Tenure',0,10)
num_of_products=st.slider('Number of products',1,4)
has_cr_card=st.selectbox('Has Credit Card',[0,1])
is_active_member=st.selectbox('Is Active Member',[0,1])

#prepare the input data
input_data=pd.DataFrame({
    'CreditScore':[credit_score],
    'Gender':[label_enc_gender.transform([gender])[0]],
    'Age':[age],
    'Tenure':[tenure],
    'Balance':[balance],
    'NumOfProducts':[num_of_products],
    'HasCrCard':[has_cr_card],
    'IsActiveMember':[is_active_member],
    'EstimatedSalary':[estimated_salary]
})

geo_encoded= onehot_enc_geo.transform([[geography]]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=onehot_enc_geo.get_feature_names_out(['Geography']))

input_data=pd.concat([input_data.reset_index(drop=True),geo_encoded_df],axis=1)

input_data_scaled=scaler.transform(input_data)

prediction=model.predict(input_data_scaled)
prediction_proba=prediction[0][0]

st.write(f"Churn porb:{prediction_proba:.2f}")

if prediction_proba>0.5:
  st.write('The customer is likely to churn')
else:
  st.write('The customer is not likely to churn')
